services:
  wedding-app:
    build: .
    restart: always
    ports:
      - "8000:8080"
    env_file:
      - .env.docker
    volumes:
      - ./data:/app/data  # This saves your database if the container restarts
